### ISSUE TITLE
Tests reverted to NQL

### ISSUE THREAD

**Issue by jamesjer** [laurentbartholdi/lpres#2]
In the 0.3.1 release, the tests in the tst directory loaded the LPRES package, used the modern Test() function, and passed.  In the 0.4.0 release, the tests attempt to load the NQL package, use the old ReadTest() function, and mostly fail.  Was a commit lost when moving git repositories?

**Comment by laurentbartholdi** [comment]
Thanks, no idea what happened but I just put them back.
