### ISSUE TITLE
Release improved testing

### ISSUE THREAD

**Issue by olexandr-konovalov** [laurentbartholdi/lpres#5]
Please consider releasing 0.4.2 with incorporated #3 - this will help to detect that the test passes in e.g. https://travis-ci.org/gap-system/gap-docker-pkg-tests-master-staging/jobs/311358767

**Comment by laurentbartholdi** [comment]
Done.

**Comment by olexandr-konovalov** [comment]
@laurentbartholdi thanks. However, the version on webpage differ from the version in https://github.com/gap-packages/lpres/blob/master/PackageInfo.g, and this worries me. Are you using ReleaseTools and GitHubPagesForGAP by @fingolfin for the release?

**Comment by laurentbartholdi** [comment]
Strange, I use ReleaseTools and GitHubPagesForGAP. The doc shows 0.4.2 on
my system.

**Comment by olexandr-konovalov** [comment]
@laurentbartholdi it has been updated in gh-pages branch but not in master. Perhaps some step from the instructions was missing?
