### ISSUE TITLE
README issues

### ISSUE THREAD

**Issue by fingolfin** [laurentbartholdi/lpres#9]
The README instructs one to do `ReadPackage("lpres","tst/testall.gi");` but that doesn't work anymore, as the file is now called `tst/testall.g`, so the "i" needs to be dropped.

Moreover, it seems @alex-konovalov added some Markdown to the README for showing the Travis & Codecov status, but that makes no sense in a file which is no Markdown. The quickest fix is to just remove the top three lines of the README again. Alternatively, one could rename it to `README.md`, but then the `README_URL` in `PackageInfo.g` must also be updated, and of course one should make sure the document actually renders nicely as markdown (e.g. adjust section titles, examples etc. if necessary).

**Comment by olexandr-konovalov** [comment]
I've anticipated when adding status badges that it will be converted to Markdown later - that would be my preference, and the case for many packages already.
